# Generated by Django 4.2.21 on 2025-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regional',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='registrohora',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='regional',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
